# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    export MAVEN_POM=pom.xml
    echo $MAVEN_POM
  displayName: 'List images'

- task: Docker@2
  inputs:
    command: 'build'
    containerRegistry: 'quayServiceConnection'
    repository: 'p1987br/build-image'
    Dockerfile: '**/Dockerfile'
    tags: latest

- script: |
    docker images
  displayName: 'List images'

- script: |
    docker run --entrypoint ./build-image.sh --privileged --name dummy quay.io/p1987br/build-image
  displayName: 'Run a docker'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
